### PR TITLE
Linting; Updates

### PR DESCRIPTION
**Pull request by mckelvey**
This PR adds linting, fixes and updates to the stack, excluding update for the contract stack, since that’s (probably) in development.

### CODE REVIEW

**Review by brolag — APPROVED** [review]
Thanks!

**Comment by mckelvey** [comment]
Thanks @brolag — I’m going to wait to merge until @edderrd has refreshed (and I can follow up here if needed) and I can get the Chromatic secret in to make sure that the workflow is valid.

**Comment by edderrd** [comment]
@mckelvey sorry for the conflicts 😅

**Comment by mckelvey** [comment]
No worries @edderrd — conflicts are all part of the game! :)

**Pull request merged**
